// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: tests/grpcgateway/proto/usersv1/users.proto

// Package users.v1 is a tiny example service used by the spisql
// grpc-gateway e2e tests. It is NOT part of the public spisql API.
//
// The service has a single List RPC whose request embeds
// spisql.v1.ListQuery — exactly the shape end users are expected to
// adopt for their own list endpoints.

package usersv1

import (
	spisqlv1 "github.com/arten331/spisql/proto/spisqlv1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *spisqlv1.ListQuery    `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_tests_grpcgateway_proto_usersv1_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tests_grpcgateway_proto_usersv1_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_tests_grpcgateway_proto_usersv1_users_proto_rawDescGZIP(), []int{0}
}

func (x *ListUsersRequest) GetQuery() *spisqlv1.ListQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_tests_grpcgateway_proto_usersv1_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_tests_grpcgateway_proto_usersv1_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_tests_grpcgateway_proto_usersv1_users_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*User                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_tests_grpcgateway_proto_usersv1_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tests_grpcgateway_proto_usersv1_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_tests_grpcgateway_proto_usersv1_users_proto_rawDescGZIP(), []int{2}
}

func (x *ListUsersResponse) GetItems() []*User {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListUsersResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_tests_grpcgateway_proto_usersv1_users_proto protoreflect.FileDescriptor

const file_tests_grpcgateway_proto_usersv1_users_proto_rawDesc = "" +
	"\n" +
	"+tests/grpcgateway/proto/usersv1/users.proto\x12\busers.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19proto/spisqlv1/list.proto\">\n" +
	"\x10ListUsersRequest\x12*\n" +
	"\x05query\x18\x01 \x01(\v2\x14.spisql.v1.ListQueryR\x05query\"X\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"O\n" +
	"\x11ListUsersResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.users.v1.UserR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total2[\n" +
	"\x05Users\x12R\n" +
	"\x04List\x12\x1a.users.v1.ListUsersRequest\x1a\x1b.users.v1.ListUsersResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/usersBDZBgithub.com/arten331/spisql/tests/grpcgateway/proto/usersv1;usersv1b\x06proto3"

var (
	file_tests_grpcgateway_proto_usersv1_users_proto_rawDescOnce sync.Once
	file_tests_grpcgateway_proto_usersv1_users_proto_rawDescData []byte
)

func file_tests_grpcgateway_proto_usersv1_users_proto_rawDescGZIP() []byte {
	file_tests_grpcgateway_proto_usersv1_users_proto_rawDescOnce.Do(func() {
		file_tests_grpcgateway_proto_usersv1_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_grpcgateway_proto_usersv1_users_proto_rawDesc), len(file_tests_grpcgateway_proto_usersv1_users_proto_rawDesc)))
	})
	return file_tests_grpcgateway_proto_usersv1_users_proto_rawDescData
}

var file_tests_grpcgateway_proto_usersv1_users_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tests_grpcgateway_proto_usersv1_users_proto_goTypes = []any{
	(*ListUsersRequest)(nil),   // 0: users.v1.ListUsersRequest
	(*User)(nil),               // 1: users.v1.User
	(*ListUsersResponse)(nil),  // 2: users.v1.ListUsersResponse
	(*spisqlv1.ListQuery)(nil), // 3: spisql.v1.ListQuery
}
var file_tests_grpcgateway_proto_usersv1_users_proto_depIdxs = []int32{
	3, // 0: users.v1.ListUsersRequest.query:type_name -> spisql.v1.ListQuery
	1, // 1: users.v1.ListUsersResponse.items:type_name -> users.v1.User
	0, // 2: users.v1.Users.List:input_type -> users.v1.ListUsersRequest
	2, // 3: users.v1.Users.List:output_type -> users.v1.ListUsersResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tests_grpcgateway_proto_usersv1_users_proto_init() }
func file_tests_grpcgateway_proto_usersv1_users_proto_init() {
	if File_tests_grpcgateway_proto_usersv1_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_grpcgateway_proto_usersv1_users_proto_rawDesc), len(file_tests_grpcgateway_proto_usersv1_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tests_grpcgateway_proto_usersv1_users_proto_goTypes,
		DependencyIndexes: file_tests_grpcgateway_proto_usersv1_users_proto_depIdxs,
		MessageInfos:      file_tests_grpcgateway_proto_usersv1_users_proto_msgTypes,
	}.Build()
	File_tests_grpcgateway_proto_usersv1_users_proto = out.File
	file_tests_grpcgateway_proto_usersv1_users_proto_goTypes = nil
	file_tests_grpcgateway_proto_usersv1_users_proto_depIdxs = nil
}
