// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/spisqlv1/list.proto

// Package spisql.v1 is the canonical wire schema for spisql list queries.
//
// Embed ListQuery in your own request messages alongside business-specific
// fields. The shape is grpc-gateway-friendly: `filter` is a single
// URL-parameter-shaped string the gateway proxies through verbatim, while
// `sort`, `limit`, and `offset` map onto typed proto fields.
//
// HTTP wire (via grpc-gateway):
//
//   GET /v1/users?filter=name%3Dvasya%26id%5Bin%5D%3D1&sort=-created_at&limit=25
//
// See github.com/arten331/spisql for parser semantics.

package spisqlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListQuery carries the four spisql wire-level parameters. Embed it in
// your own request messages; the server-side handler converts it via
// transport/grpc.Parse into a *spisql.Query.
type ListQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stripe-style flat bracket-form filter expression — a query-string
	// fragment. The client URL-encodes it once so it survives as a single
	// HTTP query parameter (e.g. "name=vasya&id[in]=1&status[ne]=deleted").
	//
	// See parser package for the full operator set.
	Filter string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// Comma-separated sort list, with `-` prefix marking DESC. Example:
	// "-created_at,name". Empty means no explicit ordering.
	Sort string `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	// Page size. Server caps via parser.Options.MaxLimit (default 100).
	// Zero means "use server default" (parser.Options.DefaultLimit, 10).
	Limit uint64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Number of rows to skip. Zero is the canonical first page.
	Offset        uint64 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuery) Reset() {
	*x = ListQuery{}
	mi := &file_proto_spisqlv1_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuery) ProtoMessage() {}

func (x *ListQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spisqlv1_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuery.ProtoReflect.Descriptor instead.
func (*ListQuery) Descriptor() ([]byte, []int) {
	return file_proto_spisqlv1_list_proto_rawDescGZIP(), []int{0}
}

func (x *ListQuery) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListQuery) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListQuery) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListQuery) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_proto_spisqlv1_list_proto protoreflect.FileDescriptor

const file_proto_spisqlv1_list_proto_rawDesc = "" +
	"\n" +
	"\x19proto/spisqlv1/list.proto\x12\tspisql.v1\"e\n" +
	"\tListQuery\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\x12\x12\n" +
	"\x04sort\x18\x02 \x01(\tR\x04sort\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x04R\x06offsetB4Z2github.com/arten331/spisql/proto/spisqlv1;spisqlv1b\x06proto3"

var (
	file_proto_spisqlv1_list_proto_rawDescOnce sync.Once
	file_proto_spisqlv1_list_proto_rawDescData []byte
)

func file_proto_spisqlv1_list_proto_rawDescGZIP() []byte {
	file_proto_spisqlv1_list_proto_rawDescOnce.Do(func() {
		file_proto_spisqlv1_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_spisqlv1_list_proto_rawDesc), len(file_proto_spisqlv1_list_proto_rawDesc)))
	})
	return file_proto_spisqlv1_list_proto_rawDescData
}

var file_proto_spisqlv1_list_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_spisqlv1_list_proto_goTypes = []any{
	(*ListQuery)(nil), // 0: spisql.v1.ListQuery
}
var file_proto_spisqlv1_list_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_spisqlv1_list_proto_init() }
func file_proto_spisqlv1_list_proto_init() {
	if File_proto_spisqlv1_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_spisqlv1_list_proto_rawDesc), len(file_proto_spisqlv1_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_spisqlv1_list_proto_goTypes,
		DependencyIndexes: file_proto_spisqlv1_list_proto_depIdxs,
		MessageInfos:      file_proto_spisqlv1_list_proto_msgTypes,
	}.Build()
	File_proto_spisqlv1_list_proto = out.File
	file_proto_spisqlv1_list_proto_goTypes = nil
	file_proto_spisqlv1_list_proto_depIdxs = nil
}
